AMERICAN/Controllers/Display/Header/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AMERICAN.Models;

namespace AMERICAN.Controllers.Display.Header
{
    public class HeaderController : Controller
    {
        private AMERICANContext db = new AMERICANContext();
        // GET: Header
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult ControlHeader()
        {
            var tblconfig = db.tblConfigs.First();
            return PartialView(tblconfig);
        }
        public PartialViewResult PartialSearch()
        {
            return PartialView();
        }
        public PartialViewResult PartialnVar()
        {
            return PartialView(db.tblConfigs.FirstOrDefault());
        }
      public PartialViewResult PartialMenu()
        {
            var listParent = db.tblGroupProducts.Where(p => p.Active == true && p.Level.Length == 5).OrderBy(p => p.Ord).ToList();
            string chuoi = "";
            chuoi += "<div class=\"Menu\">";
            chuoi += "<ul class=\"ul1\">";
            chuoi += "<li class=\"li1\">";
            chuoi += "<a href=\"/san-pham-americanstandard-dong-bo\" title=\"Sản phẩm american  standard dồng bộ\"><span></span> Sản phẩm đồng bộ</a>";
            chuoi += "</li>";
            for (int i = 0; i < listParent.Count;i++ )
            {
             
                chuoi += "<li class=\"li1\">";
                chuoi += "<a href=\"/0/" + listParent[i].Tag + "\" title=\"" + listParent[i].Name + "\"><span style=\"background:url(" + listParent[i].iCon + ") no-repeat\"></span>" + listParent[i].Name + "</a>";
                string level = listParent[i].Level.ToString();
                var listchild = db.tblGroupProducts.Where(p => p.Active == true && p.Level.Substring(0, level.Length) == level && p.Level != level).OrderBy(p => p.Ord).ToList();
                if (listchild.Count > 0)
                {
                    chuoi += "<ul class=\"ul2\">";
                    for (int j = 0; j < listchild.Count; j++)
                    {
                        chuoi += "<li class=\"li2\">";
                        chuoi += "<div class=\"tear_Menu\">";
                        chuoi += "<a href=\"/0/" + listchild[j].Tag + "\" title=\"" + listchild[j].Name + "\"><img src=\"" + listchild[j].Images + "\" alt=\"" + listchild[j].Name + "\" title=\"" + listchild[j].Name + "\" /></a>";
                        chuoi += "</div>";
                        chuoi += "<div class=\"Line\"></div>";
                        chuoi += "<a href=\"/0/" + listchild[j].Tag + "\" class=\"Name\" title=\"" + listchild[j].Name + "\">" + listchild[j].Name + "</a>";
                        chuoi += "</li>";
                    }
                    chuoi += " </ul>";
                }
                chuoi += "</li>";
              

            }
            chuoi += "</ul>";
            chuoi += "</div>";
            ViewBag.chuoi = chuoi;
                return PartialView();
        }
        public PartialViewResult PatialHeader()
      {
          var listimageslide = db.tblImages.Where(p => p.Active == true && p.idMenu == 1).OrderByDescending(p => p.Ord).Take(4).ToList();
          string chuoislide = "";
          for (int i = 0; i < listimageslide.Count; i++)
          {
              if (i == 0)
              {
                  chuoislide += "url(" + listimageslide[i].Images + ") " + (845 * i) + "px 0 no-repeat";
              }
              else
              {

                  chuoislide += ", url(" + listimageslide[i].Images + ") " + (845 * i) + "px 0 no-repeat";
              }
          }
          ViewBag.chuoislide = chuoislide;
          var listImage = db.tblImages.Where(p => p.Active == true && p.idMenu == 6).OrderBy(p=>p.Ord).ToList();
            string chuoi="";
          for (int i = 0; i < listImage.Count;i++ )
          {
              chuoi+= " <a href=\"" + listImage[i].Url + "\" title=\"" + listImage[i].Name + "\"><img src=\"" + listImage[i].Images + "\" alt=\"" + listImage[i].Name + "\" title=\"" + listImage[i].Name + "\" /></a>";
          }
          ViewBag.chuoi = chuoi;
          return PartialView(listimageslide);
      }
    }
}

AMERICAN/Views/Header/ControlHeader.cshtml
@model AMERICAN.Models.tblConfig 
           @if(Request.Browser.IsMobileDevice)
           { 
<div id="Menu_mb">
    <a href="/" title="Trang chủ" rel="nofollow"><img src="@Model.ImageLinkLogo" alt="@Model.Name" title="@Model.Name" /></a>
    <div id="MenuMobile">
        <a href="#menu" rel="nofollow"><span></span>Danh mục</a>
    </div>
</div>
           }
<div id="Logo">
    <div id="bg_logo">
        <div id="Content_Logo">
            <a href="/" title="Trang chủ" rel="nofollow"></a>
        </div>
    </div>

</div>
<div id="Banner">
    <div id="Content_Banner">
        <div id="Center_Banner">
            <h2>@Model.Name</h2>
            <p>Hệ thống phân phân phối <span class="gr">American<span>Standard</span></span> lớn nhất Việt Nam</p>
        </div>
        <div id="Right_Banner">
            <div class="icon"></div>
            <div class="Hotlines">
                <span class="hl1">Tư vấn Online (24/7)</span>
                <span class="hl2">
                   

                        <span>@Model.PbxSell</span>
                   
                </span>
            </div>
        </div>
    </div>
</div>

AMERICAN/Views/Header/PartialMenu.cshtml
@Html.Raw(ViewBag.chuoi)

AMERICAN/Views/Header/PartialSearch.cshtml
@using (Html.BeginForm("Search", "Product", FormMethod.Post))
{

    <div class="Box_Search">
        <input type="text" name="txtSearch" class="txtSearch" placeholder="Tìm kiếm" />
        <button type="submit" name="btnSearch"  class="btnSearch"></button>
    </div>
}

AMERICAN/Views/Header/PartialnVar.cshtml
@model AMERICAN.Models.tblConfig
<div id="nVar">
    <div id="Content_nVar">
        <div id="Menu_nvar">
            <span>Danh mục sản phẩm</span>
            @{Html.RenderAction("PartialMenu", "Header");}
        </div>
        <div id="Box_Search">
            @using (Html.BeginForm("Search", "Product", FormMethod.Post))
            {
                <input type="text" name="txtSearch" class="txtSearch" id="txtSearch" />
                <button type="submit" name="btnSearch" id="btnSearch" class="btnSearch">TÌM</button>
            }
        </div>
        <div id="boxsale">
            <a href="/ban-tin-khuyen-mai" title="Khuyến mại">
                <img src="~/Content/Display/iCon/update/KM-con.gif" />
            </a>
        </div>
        <div id="BoxTime">
            Thời gian Mở cửa : <span>@Model.TimeWork</span>
        </div>
        <div id="BoxOrder">
            @if (Session["soluong"] != "" && Session["soluong"] != null)
            {


                <a href="/Order/OrderIndex" title="Giỏ hàng" class="CountOf"><span class="icon"></span>Giỏ hàng <span>có @Session["soluong"].ToString() sp</span></a>
            }
            else
            {
                <a href="/" title="Giỏ hàng" class="CountOf" rel="nofollow"><span class="icon"></span>Giỏ hàng <span>có 0 sp</span></a>
            }

        </div>
    </div>

</div>

AMERICAN/Views/Header/PatialHeader.cshtml
@model IEnumerable<AMERICAN.Models.tblImage>
<div id="Header">
    <div id="MainMenu">
        @{Html.RenderAction("PartialMenu", "Header");}
    </div>
    <div id="Slide">
        <div id="slideshow">
            <div class="container">
                <div class="c_slider" style="background:@Html.Raw(ViewBag.chuoislide)"></div>
                <div class="slider">
                    @foreach (var item in Model)
                    {
                        <figure>
                            <img src="@item.Images" alt="@item.Name" title="@item.Name" width="845" height="300" />
                        </figure>
                    }
                </div>
            </div>
            <span id="timeline"></span>
        </div>
    </div>
</div>
<div class="uudai">
  @Html.Raw(ViewBag.chuoi)
</div>