AMERICAN/Controllers/Admin/Maps/MapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AMERICAN.Models;
using PagedList;
using PagedList.Mvc;
using System.Globalization;
using System.ComponentModel.DataAnnotations;
namespace AMERICAN.Controllers.Admin.Maps
{
    public class MapsController : Controller
    {
        private AMERICANContext db = new AMERICANContext();

        //
        // GET: /Maps/

        public ActionResult Index(int? page )
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            var ListMaps = db.tblMaps.ToList();

            const int pageSize = 20;
            var pageNumber = (page ?? 1);
            // Thiết lập phân trang
            var ship = new PagedListRenderOptions
            {
                DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                DisplayLinkToLastPage = PagedListDisplayMode.Always,
                DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                DisplayLinkToNextPage = PagedListDisplayMode.Always,
                DisplayLinkToIndividualPages = true,
                DisplayPageCountAndCurrentLocation = false,
                MaximumPageNumbersToDisplay = 5,
                DisplayEllipsesWhenNotShowingAllPageNumbers = true,
                EllipsesFormat = "&#8230;",
                LinkToFirstPageFormat = "Trang đầu",
                LinkToPreviousPageFormat = "«",
                LinkToIndividualPageFormat = "{0}",
                LinkToNextPageFormat = "»",
                LinkToLastPageFormat = "Trang cuối",
                PageCountAndCurrentLocationFormat = "Page {0} of {1}.",
                ItemSliceAndTotalFormat = "Showing items {0} through {1} of {2}.",
                FunctionToDisplayEachPageNumber = null,
                ClassToApplyToFirstListItemInPager = null,
                ClassToApplyToLastListItemInPager = null,
                ContainerDivClasses = new[] { "pagination-container" },
                UlElementClasses = new[] { "pagination" },
                LiElementClasses = Enumerable.Empty<string>()
            };
            ViewBag.ship = ship;
            return View(ListMaps.ToPagedList(pageNumber, pageSize));
        }

  

        public ActionResult Edit(int id = 0)
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            tblMap tblmap = db.tblMaps.Find(id);
            if (tblmap == null)
            {
                return HttpNotFound();
            }
            return View(tblmap);
        }

        //
        // POST: /Maps/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(tblMap tblmap)
        {
            if (ModelState.IsValid)
            {
                string idUser = Request.Cookies["Username"].Values["UserID"];
                tblmap.UserID = int.Parse(idUser);
                db.Entry(tblmap).State = EntityState.Modified;
                db.SaveChanges();
                #region[Updatehistory]
                Updatehistoty.UpdateHistory("Edit maps", Request.Cookies["Username"].Values["FullName"].ToString(), Request.Cookies["Username"].Values["UserID"].ToString());
                #endregion
                return RedirectToAction("Index");
            }
            return View(tblmap);
        }

      

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AMERICAN/Controllers/Display/Session/Maps/MapsDisplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AMERICAN.Models;
 namespace AMERICAN.Controllers.Display.Session.Maps
{
    public class MapsDisplayController : Controller
    {
        AMERICANContext db = new AMERICANContext();
        //
        // GET: /MapsDisplay/
        public ActionResult Index()
        {
             return View();
        }
       
        public ActionResult MapsDetail()
        {
            tblMap map = db.tblMaps.First();
            ViewBag.Title = "<title>" + map.Name + "</title>";
            ViewBag.Description = "<meta name=\"description\" content=\"" + map.Description + "\"/>";
            ViewBag.Keyword = "<meta name=\"keywords\" content=\"" + map.Name + "\" /> ";
            return View(map);

           
        }
	}
}

AMERICAN/Views/Maps/Edit.cshtml
@model AMERICAN.Models.tblMap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm())
{ 
    @Html.ValidationSummary(true)
    <div id="InsertPoduct">
        <div class="Nvar_Content_Detail">
            <div class="Left_Nvar">
                <img src="/Content/Admin/Icon/folder.png" alt="Danh mục sản phẩm" />Edit Maps
            </div>
            <div class="Right_Nvar">
                <div id="msg" class="msg">
                    <div class="alert alert-info" id="update-message">
                    </div>
                </div>
            </div>
        </div>
        <div class="Content_Content_Detail">

            <div class="tr_1">
                <div class="left_tr1">
                    <span>Name :</span>
                </div>
                <div class="Right_tr1">
                    @Html.TextBoxFor(p => p.Name, null, new { @class = "Leght_2" }) <span class="Aler_ttxtName" style="color: #F00"></span>

                </div>
            </div>
            <div class="tr_1">
                <div class="left_tr1">
                    <span>Description:</span>
                </div>
                <div class="Right_tr1">
                    @Html.TextAreaFor(p => p.Description, new { @class = "Leght_6" })

                </div>
            </div>
            <div class="tr_1">
                <div class="left_tr1">
                    <span>Content:</span>
                </div>
                <div class="Right_tr1">
                    @Html.TextAreaFor(p => p.Content, new { @class = "Leght_6" })

                </div>
            </div>



            <div class="tr_1">
                <div class="left_tr1">
                </div>
                <div class="Right_tr1">
                    <button type="submit" id="btnAdd" name="btnAdd" class="btnAdd">Edit</button>
                </div>
            </div>
        </div>

    </div>
}


<script type="text/javascript">
    var editor;
    function createEditor(languageCode, id) {
        var editor = CKEDITOR.replace(id, {
            language: languageCode
        });
    }

    $(function () {
        createEditor('vi', 'Content');
    });

</script>

AMERICAN/Views/Maps/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<AMERICAN.Models.tblMap>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Command", "Maps", FormMethod.Post))
{
    <div id="Content_Detail">
        <div class="Nvar_Content_Detail">
            <div class="Left_Nvar">
                <img src="/Content/Admin/Icon/folder.png" alt="Danh mục sản phẩm" />Maps
            </div>

            <div class="Right_Nvar">
                <div id="msg" class="msg">
                    <div class="alert alert-info" id="update-message">
                        <span>@Html.Raw(ViewBag.result)</span>
                    </div>
                </div>
            </div>
        </div>


        <div class="/Content_Content_Detail">
            <div class="Nvar_1">


                <div class="clo_2" style="width: 93%">Name</div>


                <div class="clo_5">Edit</div>

            </div>
            @foreach (var item in Model)
            {
                <div class="Nvar_2">


                    <div class="clo_2" style="width: 93%"><a href="/../../Maps/Edit?id=@item.id" title="@item.Name">@item.Name</a> </div>


                    <div class="clo_5">
                        <a href="/../../Maps/Edit?id=@item.id" title="Thiết bị vệ sinh AMERICAN chính hãng" class="Edit"></a>
                    </div>

                </div>
       
            }
            <div class="nVar_3">
                <div class="clo_1">
                    -
                </div>

                <div class="clo_7">
                </div>


            </div>

        </div>

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, sortOrder = ViewBag.CurrentSortOrder, sortName = ViewBag.CurrentSortName, sortLevel = ViewBag.CurrentSortLevel }), (PagedListRenderOptions)ViewBag.ship)

    </div>
}